name: Test PowerShell Utility

on:
  push:
    branches: [ sample ]
  pull_request:
    branches: [ sample ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pester
        run: Install-Module -Name Pester -Force -Scope CurrentUser
        shell: pwsh
      - name: Run Tests
        run: pwsh -c "Invoke-Pester ./SumUtility.Tests.ps1"
